name: Unit testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  create-development-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      